name: Schedule Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # каждые 6 часов

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install jsdom axios

      - name: Install LibreOffice
        run: sudo apt-get update && sudo apt-get install -y libreoffice

      - name: Run script
        env:
          GETCOURSE_COOKIE: ${{ secrets.GETCOURSE_COOKIE }}
        run: node scripts/update-schedule.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Schedule/
          git commit -m "Обновлено расписание" || echo "Нет изменений"
          git push
